"""add name and created field in apikey

Revision ID: 2b096a17af29
Revises: a7a099d39dd9
Create Date: 2023-03-28 13:35:24.637418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b096a17af29'
down_revision = 'a7a099d39dd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('name', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('created', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'created')
    op.drop_column('api_keys', 'name')
    # ### end Alembic commands ###
