"""add log table

Revision ID: 44c801aab88d
Revises: a8b616e25f8d
Create Date: 2023-03-21 15:39:23.505937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c801aab88d'
down_revision = 'a8b616e25f8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
