"""delete credit orphan

Revision ID: a7a099d39dd9
Revises: 3149c0ca2d33
Create Date: 2023-03-28 12:55:53.422749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a099d39dd9'
down_revision = '3149c0ca2d33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'credit_tracking', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_constraint(None, 'credit_tracking', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    # ### end Alembic commands ###
